### ISSUE TITLE
Roadmap for 2019

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#148]
Hi all! 

In the last months we were focus on improve the codebase with tests, mostly e2e test and CI. 

Now we are more confidents on the source code and it's easier to validate PRs and merge new contributions. I think is a good time to discuss about the roadmap for NodeGoat in the following months. 

Right now we are close to publish release 1.4 that includes (e2e and ci). I just want to suggest some possible targets for the following releases.

**Release 1.5**
Main goal: 
- Improve source code

Pending PRs (Update/review):
- [ ] change app.csp() with contentSecurityPolicy() #119
- [ ] replace helmet.xframe() with helmet.frameguard(), xframe is deprecated #118
- [ ] Adding secondary /api/login route for JSON user login processing #91

Targets:
- [ ] Migration to es6+
- [ ] Migration to node 12 (support for Node 12|10|8)
- [ ] Upgrade dependencies to secure latest versions in `package.json`, _see: #82_
- [ ] migration from `Grunt` to `npm scripts`
- [ ] Migration from `Mocha` to `Jest` and add Unit tests
- [ ] Migration from `Swig` [Deprecated](https://www.npmjs.com/package/swig) to `ejs`
- [ ] Migration from `bcrypt-nodejs` [Deprecated](https://www.npmjs.com/package/bcrypt-nodejs) to `bcrypt`
- [ ] Improve Cypress and travis scripts, like [cy.exec validation](https://github.com/OWASP/NodeGoat/blob/master/test/e2e/support/commands.js#L28)
- [ ] `Forever` is not in use, let's move to Nodemon as npm script
- [ ] We need a definitive cool super-fancy logo! 💪
- [ ] Let's simplify the configuration steps
- [ ] Update README and relevant documentation
- [ ] Let's add multi-language support for [The Tutorial Guide](https://nodegoat.herokuapp.com/tutorial), this will help the use of Nodegoat as a very effective workshop tool for non-english speakers
- [ ] Include [ZAP testing](https://youtu.be/IVLpmCtiPZ0?t=2447) in CI workflow, _See: #34_
- [ ] Migration to [purpleteam](https://gitlab.com/purpleteam-labs) suggested by @binarymist in [issue #142](https://github.com/OWASP/NodeGoat/issues/142#issuecomment-500380900)
- [ ] Add code review checklist #37
- [ ] Harmonize the JS Style with [Standard](https://standardjs.com/) and [Prettier](https://prettier.io)
- [ ] Let's add git hooks for linting and testing with [Husky](https://github.com/typicode/husky)
- [ ] Example / Implementation for noSQL Injection #90 by @lirantal 

**Release 1.6**
Main goals/ideas suggested by @ckarande: 
- Upgrade to the latest OWASP Top 10 (#99)
> Honestly, I didn't find certain new additions to OWASP top 10 2017 very relevant to Node.js usage (e.g, not many Node.js users deal with XML) but in the sprit of demonstrating the top 10, it could be worth explaining / incorporating the latest OWASP top 10 list. I would like to retain some of the existing vulnerabilities from the OWASP Top 10 2013 version that are not in the 2017 version (such as CSRF, Insecure Redirects, etc) . So we can make two sections on the tutorial site - OWASP Top 10 2017, and Beyond OWASP Top 10.

- Provide versions that are close to real world Node.js usage

> As you may know, current version of Nodegoat uses templates for rendering UI and cookie based stateful session. This architecture is good for beginners to have the least resistance to start diving into the security specific concepts. However, I would like to provide two additional versions of NodeGoat that are close to real world Node.js apps and demonstrate security vulnerabilities in the context of these architectures:
> - Architecture 2: Using client side rendering with React (or Vue/Angular) and stateless session management using JWT. As part of this upgrade the UI build system to use webpack / UI framework specific build CLI.
> -  Architecture 3: various services broken down into individually deployable micro services.
_Also check: #38_

If we have a clear roadmap it will super easy to reclute contributors and provide them a clear path to follow :-)

I will try to setup a local Hackathon in Madrid to reclute new contributors and close some issues 👍 

In order to keep all smooth and simple to review, I will suggest to work using issues per feature and link those issues to small PRs and commit using GitFlow (branches per release) so we can concentrate all the PRs per release. And then a final PR from the release branch to the master in order to upgrade package version and deploy in Heroku.

What do you think? Do you agree for the targets/items for release 1.5? I think that we need to discuss a lot for 1.6 as now it is very conceptual

**Comment by ckarande** [comment]
A very good compilation of next tasks and release roadmap. It looks good to me.

I just created release 1.4 and we are all set to start rolling out tasks you listed for Release 1.5. I agree that items for 1.5 are well defined and we can proceed with those. As we proceed, let's create issues for each item in the list and add it to corresponding [milestones](https://github.com/OWASP/NodeGoat/milestones?with_issues=no).

I have added you to the list of collaborators for the project 🎉🎉. Thanks for your contributions and looking forward to work together to make NodeGoat even more valuable resource for the community.

**Comment by UlisesGascon** [comment]
thanks a lot @ckarande !! 🤗 

Can you add me extra rights for manage issue label creation and milestone assignation? maybe projects, too?  :-)

**Comment by ckarande** [comment]
Of course. Can you please check if you have the necessary rights now.

**Comment by UlisesGascon** [comment]
Oh yeah! Now it is perfect ^^

**Comment by UlisesGascon** [comment]
Hi all!

I just added new issues for release 1.6 and rename this issue for 2020. 

I will try to expend some time the following two weeks to remap the current status for 1.5 and push some code to speed up the release.

**Comment by ckarande** [comment]
Sounds great. Thanks @UlisesGascon

**Comment by binarymist** [comment]
May be worth updating the checklist? [purpleteam](https://purpleteam-labs.com/) has been testing NodeGoat for several years now
