### ISSUE TITLE
Migration to node 12

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#150]
### Context
- This is part of `release-1.5` #148 
- Critical task

### Tasks
- [x] Add support for Node 12
- [x] Add support for Node 10
- [x] Add support for Node 8
- [x] Update `travis.yaml` with the builds for those environments
- [x] Update the `readme.md` with the relevant info

### Assignation
- This tasks is open for assignation, just claim it (as reply to this) and submit your PR ;-)

### Important
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)

**Comment by binarymist** [comment]
Pretty sure last time I suggested we upgrade @ckarande wasn't that keen. Hopefully this has changaed?

**Comment by ckarande** [comment]
@binarymist Yes, I know this item has been in the list for a while. I am good to take it now. Having the integration test coverage now allows us to do the necessary validations in an efficient way. 👍

**Comment by UlisesGascon** [comment]
This was closed by #160
