### ISSUE TITLE
We need a CONTRIBUTING Guide and CoC

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#151]
### Context
- This is part of `release-1.5` #148 
- Critical task

### Tasks
- [ ] Define a good a contributing guide (requirements/discussion)
- [ ] Add the information to `CONTRIBUTING.md`
- [ ] Let's agree on a good Code of Conduct (CoC)
- [ ] Add the CoC to the `CONTRIBUTING.md`
- [ ] Update the `README.md` with the new CoC and Contributing guide

### Discussion

**CoC**
- I suggest to use the standard [Contributor Covenant](https://www.contributor-covenant.org/) as it is available in [many languages](https://www.contributor-covenant.org/translations) and it is widely adopted by [+300k repos](https://github.com/search?l=Markdown&q=%22Contributor+Covenant%22+fork%3Afalse&type=Code). I believe that [1.4 (latest version)](https://www.contributor-covenant.org/version/1/4/code-of-conduct) is cool for us. Good [F.A.Q](https://www.contributor-covenant.org/faq) too.

> In the interest of fostering an open and welcoming environment, we as contributors and maintainers pledge to making participation in our project and our community a harassment-free experience for everyone, regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.
- For extra info on ["Why do I need a code of conduct?, etc..."](https://opensource.guide/code-of-conduct/)

**Contributing**
- I believe that we can use this [good example](https://gist.github.com/PurpleBooth/b24679402957c63ec426) wrote by @PurpleBooth and later on we can add extra info about how do we want to manage GitFlow, merges, PRs, Issues labels... 
- Other cool examples:
   - The Atom editor [contribution guidelines](https://github.com/atom/atom/blob/master/CONTRIBUTING.md).
   - The Ruby on Rails [contribution guidelines](https://github.com/rails/rails/blob/master/CONTRIBUTING.md).
   - The Open Government [contribution guidelines](https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md).
- The implementation seems [super simple](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors).

### Assignation
- This tasks is an important decision making, let's open discussion. I will transfer all the decisions to the files, but let's @ckarande help us to define what fits better for the project ^^

### Extra Stuff 
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)

**Comment by ckarande** [comment]
@UlisesGascon Thanks for adding this task. Yes, the Contributing Guidelines and the Code of Conduct are important as the number of contributors grow.

For CoC, I like your suggestion to use [Contributor Covenant](https://www.contributor-covenant.org/). Lets go with it.

For Contribution guidelines, right now we have [a very short section](https://github.com/OWASP/NodeGoat/blob/master/README.md#ways-to-contribute) on it. I am fine with adding a CONTRIBUTING.md and start simple by following the template created by @PurpleBooth.  Sooner than later, we should add a section on coding style guide and checks to perform before making a PR to keep the code quality consistent.

Cheers!

**Comment by UlisesGascon** [comment]
Awesome! Thanks @ckarande. I will rise a PR asap with the changes
