### ISSUE TITLE
Migration to es6+

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#152]
### Context
- This is part of `release-1.5` #148 
- Depends on #150 
- Critical task

### Tasks
- [ ] Clean Source code (JS Files)
- [ ] Migrate to ES6+ Syntaxis (Promises, Async, const/let, arrow...)
- [ ] Update the `readme.md` with the relevant info (if needed)

### Assignation
- This tasks is open for assignation, just claim it (as reply to this) and submit your PR ;-)

### Important
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)

**Comment by lucas1004jx** [comment]
I want to help with this issue :)

**Comment by UlisesGascon** [comment]
Thanks @lucas1004jx for join us! 🤗

This issue is assigned to you, please remember to refer to this issue when do you submit a PR, so we can connect the dots easily.
