### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#153]
### Context
- This is part of `release-1.5` #148 
- Context from #82 
- Critical task

### Tasks
- [ ] Upgrade dependencies to secure latest versions in `package.json`
- [ ] Validate the instalation with the local test
- [ ] Add and submit the changes in `package-lock.json`
- [ ] Add the primary depdency list to the `readme.md`
- [ ] Check that the npm tasks are working as expected
- [ ] Update the `readme.md` with the extra relevant info (if needed)

### Assignation
- This tasks is open for assignation, just claim it (as reply to this) and submit your PR ;-)

### Important
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)

**Comment by jamesleynorvil** [comment]
@UlisesGascon I have a PR for this issue

**Comment by RajvardhanT7747** [comment]
hii @UlisesGascon , |
i would love to work on this issue if available 
can you assign this issue to me ??
