### ISSUE TITLE
Let's add git hooks for linting and testing with Husky

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#154]
### Context
- This is part of `release-1.5` #148 
- Medium priority task

### Tasks
- [ ] Install `prettier` + `eslint` -> [prettier-eslint](https://github.com/prettier/prettier-eslint)
- [ ] Config the task in `package.json`
- [ ] Upload the changes in files `package*.json`
- [ ] Update the `README.md` with the relevant information

### Assignation
- This tasks is assigned to @UlisesGascon

**Comment by carlosazaustre** [comment]
I'd like to help with this issue during xmas :)

**Comment by UlisesGascon** [comment]
Awesome @carlosazaustre!! I will asign you the tasks. Please use `release-1.5` branch (It is the most stable source and the final destination)
