### ISSUE TITLE
Let's add git hooks for linting and testing

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#155]
### Context
- This is part of `release-1.5` #148 
- High priority task

### Tasks
- [ ] Install [husky](https://www.npmjs.com/package/husky)
- [ ] Config the task in `package.json`
    - [ ] pre-commit for linting task, (depends on #154) 
    - [ ] pre-push for testing task
- [ ] Upload the changes in files `package*.json`
- [ ] Update the `README.md` with the relevant information

### Assignation
- This tasks is assigned to @UlisesGascon
