### ISSUE TITLE
Add nodemon

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#156]
### Context
- This is part of `release-1.5` #148 
- Possible dependency with task (Migration to Nodec v12) #150
- Strong dependency with (Grunt Migration) #149 
- LOW task

### Tasks
- [ ] Remove `Forever` dependency as is not in use.
- [ ] Add `Nodemon` as dependency
- [ ] Add task `dev` to the package.json that allow us to reload the server on changes, [see]()
 is not in use, let's move to Nodemon as npm script
- [ ] Update the primary depdency list to the `readme.md`
- [ ] Check that the npm tasks are working as expected
- [ ] Update the `readme.md` with the extra relevant info (if needed)

### Assignation
- This tasks is assigned to @servatj as he already is assigned for #149 

### Important
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)

**Comment by UlisesGascon** [comment]
Do you agree @servatj ?

**Comment by servatj** [comment]
Yes, I Agree maybe it's worth starting with #150 and upgrade to node js 12. I will assign it to me.

**Comment by servatj** [comment]
I just noticed that @ckarande  picked #150  [https://github.com/OWASP/NodeGoat/issues/156](here) I will continue working with this #156 first an then continue with #149.

**Comment by UlisesGascon** [comment]
Fix in #161
