### ISSUE TITLE
Migration to EJS

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#157]
### Context
- This is part of `release-1.5` #148 
- MEDIUM priority task

### Tasks
Migration from Swig Deprecated to ejs
- [ ] Remove dependency `Swig` in `package.json`
- [ ] Add dependency `ejs` in `package.json`
- [ ] Configure express to use ejs as [template engine](https://scotch.io/tutorials/use-ejs-to-template-your-node-application)
- [ ] migrate all the files from `/app/views/**.html` to EJS
- [ ] Validate the instalation with the local test
- [ ] Add and submit the changes in `package-lock.json`
- [ ] Add the primary depdency list to the `readme.md`
- [ ] Check that the npm tasks are working as expected
- [ ] Update the `readme.md` with the extra relevant info (if needed)

### Assignation
- This tasks is open for assignation, just claim it (as reply to this) and submit your PR ;-)

### Important
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)

**Comment by flippedcoder** [comment]
Hi there. I'd like to work on this issue. When do you need this finished?

**Comment by UlisesGascon** [comment]
Hi @flippedcoder! 

**Super welcome aboard**. There is no deadline or pressure for this issue, so you can work on it quietly 😄 

I just assigned this issue to you. Please send the PR against branch `version-1.5` 😉.

If you have more questions.. please, ping me ^^

**Comment by flippedcoder** [comment]
@UlisesGascon Just a quick update, I've gotten the migration over to ejs finished! I'm going through and fixing all of the errors from npm run precommit. I should have a PR up for this some time next week.

**Comment by flippedcoder** [comment]
Looks like this got closed with #179
