### ISSUE TITLE
Migration to bcrypt

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#158]
### Context
- This is part of `release-1.5` #148 
- MEDIUM priority task

### Tasks
- [ ] Remove dependency `bcrypt-nodejs` in `package.json`
- [ ] Add dependency `bcrypt` in `package.json`
- [ ] Migrate file [app/data/user-dao.js](https://github.com/OWASP/NodeGoat/blob/master/app/data/user-dao.js) to bcrypt
- [ ] Validate the instalation with the local test
- [ ] Add and submit the changes in `package-lock.json`
- [ ] Add the primary dependency list to the `readme.md`
- [ ] Check that the npm tasks are working as expected
- [ ] Update the `readme.md` with the extra relevant info (if needed)

### Assignation
- This tasks is open for assignation, just claim it (as reply to this) and submit your PR ;-)

### Important
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)
`app/data/user-dao.js`

**Comment by PeterWunderlich** [comment]
Hi all! 
As i want to get more into FOSS I stumbled upon this project again and saw this issue. I would claim it for now and would be glad provide the PR by the end of this week, if it's okay? :)

If so, i'll do the migration from [bcrypt-nodejs](https://www.npmjs.com/package/bcrypt-nodejs) to [bcrypt](https://www.npmjs.com/package/bcrypt).

**Comment by ckarande** [comment]
@PeterWunderlich thank you for your interest in contributing to the project. Yes, you are very welcome to make the PR. I have assigned it to you 👍

**Comment by UlisesGascon** [comment]
Thank you, @PeterWunderlich! :-)

**Comment by PeterWunderlich** [comment]
Hey @ckarande & @UlisesGascon,
the migration is finished from my part but i have 2 final questions regarding the tasks:

1. Add the primary dependency list to the readme.md: Shall i add a list of the dependencies (devDependencies exlucded) with a short explanation to the README.md? I would add the list before the "How to Setup Your Copy of NodeGoat" chapter.
2. I've run into a few problems on my Windows machine executing the npm scripts, as "NODE_ENV" is not a known command for my OS. Usually i use [cross-env](https://www.npmjs.com/package/cross-env) for convenience. Do you want me to add this, do you have any other suggestions or did I use something wrong? Maybe this could become a new issue? :)

As I'm finished i would create a PR heading to the "OWASP:release-1.5" branch or do you want me to merge elsewhere?

Thanks for your help. :)

**Comment by UlisesGascon** [comment]
Hi @PeterWunderlich! 

1. Don't worry about the README.md dependencies. I will include an script that will autodocument that part for us.

2. Feel free to add `cross-env` to add support for windows users.

3. PR to `OWASP:release-1.5` is perfect 👍 

Thanks a lot for your support!

**Comment by jantaylor** [comment]
It looks like this task is already assigned and has not been implemented. Would you like me to take it on instead?

**Comment by PeterWunderlich** [comment]
@jantaylor sure, feel free to take over.

**Comment by jantaylor** [comment]
@PeterWunderlich I've submitted the PR if you want to look it over and give your review. 
@UlisesGascon, the PR is ready for your review as well.

**Comment by lirantal** [comment]
I've pinged Jan in the original PR. Let's see if he is able to follow-up first.

**Comment by snow-kluster** [comment]
> I've pinged Jan in the original PR. Let's see if he is able to follow-up first.

Ok

**Comment by snow-kluster** [comment]
Is it alright if I open a PR as I think, I have fixed this issue as well as issue #271 and ran **"npm run precommit"** and fixed all those errors.

**Comment by snow-kluster** [comment]
Are there any updates about the PR

**Comment by jantaylor** [comment]
@snow-kluster I haven't gotten any indication that the maintainers wanted to merge my PR.
