### ISSUE TITLE
 Improve Cypress script

### ISSUE THREAD

**Issue by UlisesGascon** [OWASP/NodeGoat#159]
### Context
- This is part of `release-1.5` #148 
- Critical task

### Tasks
- [ ] Improve the speed of the e2e tests (almost 8 minutes now). Maybe videos are generated (ci/local envs)
- [ ] Add test that are missing (fast check)
- [ ] Remove unnecessary/repetitive tests
- [ ] Improve the [command `dbReset`](https://github.com/OWASP/NodeGoat/blob/master/test/e2e/support/commands.js#L28). Missing validation due Travis conflicts
- [ ] Check that the npm tasks are working as expected
- [ ] Update the `readme.md` with the extra relevant info (if needed)

### Assignation
- This tasks is open for assignation, just claim it (as reply to this) and submit your PR ;-)

### Important
- Check the current roadmap #148
- Don't forget to check the [Contributing Guidelines](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md) and follow the [Code of Conduct](https://github.com/OWASP/NodeGoat/blob/master/CONTRIBUTING.md)

**Comment by rcowsill** [comment]
I'd like to help with this. I've been looking at some performance improvements to the tests and also making them more reliable.

**Comment by rcowsill** [comment]
To start, I'd like to make pull requests for two fixes that should resolve the signup test flakiness:
- [ ] Make db-reset.js wait for `dropCollections` to complete before inserting new data
- [ ] Set necessary env vars in `docker-compose.yml` to make the web service use the mongo service (instead of mongolab)

The first one affects branches `master` and `feature/187`. The second currently only affects `feature/187`, because `master` isn't using docker in Travis.

I have more to follow, but these are higher priority because they make the tests reliable. Making these changes should save a lot of time looking into false build failures.

@UlisesGascon, which branch(es) would you prefer the pull request(s) to be made against?

**Comment by rcowsill** [comment]
Pull request for the dropCollections fix is open: #214

**Comment by rcowsill** [comment]
> To start, I'd like to make pull requests for two fixes that should resolve the signup test flakiness:

Both these fixes were merged into `master` in c44bbd64cac539bb5d24f3c4a65025f7fc1690d2.

The fix to set MONGODB_URI in docker builds needs to be merged into `feature/187` before January 12, 2021. On that date the mLab database currently used by CI in this branch will be shut down, causing all subsequent build jobs to fail.

**Comment by rcowsill** [comment]
Just made PR #230 which adds video recording/upload to the github actions CI workflow.

Video recording is off by default for local test runs, but can be activated like this if needed:
`npm run test:ci -- --config video=true`
or:
`npx cypress run --config video=true`
